// import cosmatic from "./../assets/cosmat1.jpg";
// import cosp1 from "./../assets/cosp2.png";
import mobile from "./../assets/mobile1.jpg";
import Kitchen from "./../assets/Kitchen1.jpg";
import perfum from "./../assets/perfum.webp";
import perfum2 from "./../assets/Kitchen1.jpg"; 
import perfum3 from "./../assets/perfum.webp"; 

export const productsData = {
  cosmetics: [
    {
      id: 1,
      name: "Lipstick",
      price: 120,
      img: perfum,
      images: [perfum, perfum2, perfum3], // Array of images
      hotsale: true,
      category: "cosmetics",
      inStock: true,
      description:
        "Rich pigmented lipstick with long-lasting formula. Perfect for everyday use and special occasions.",
      categories: ["Beauty Glow", "Makeup"],
      tags: ["Lipstick", "Cosmetics", "Vegan"],
    },
    {
      id: 2,
      name: "Face Cream",
      price: 450,
      img: perfum2,
      images: [perfum2, perfum, perfum3],
      newarrival: true,
      category: "cosmetics",
      inStock: true,
      description:
        "Hydrating face cream with natural ingredients to nourish and protect your skin.",
      categories: ["Skincare", "Moisturizer"],
      tags: ["Cream", "Facial Care", "Anti-Aging"],
    },
    {
      id: 3,
      name: "Eyeliner",
      price: 300,
      img: perfum3,
      images: [perfum3, perfum, perfum2],
      category: "cosmetics",
      inStock: false,
      description:
        "Precision eyeliner for sharp, defined lines. Waterproof and smudge-proof.",
      categories: ["Makeup", "Eye Makeup"],
      tags: ["Eyeliner", "Waterproof", "Long Lasting"],
    },
    {
      id: 4,
      name: "Foundation",
      price: 800,
      img: perfum,
      images: [perfum, perfum2, perfum3],
      category: "cosmetics",
      inStock: true,
      description:
        "Full-coverage foundation that blends seamlessly into the skin. Available in multiple shades.",
      categories: ["Makeup", "Base Makeup"],
      tags: ["Foundation", "Full Coverage", "Matte Finish"],
    },
    {
      id: 5,
      name: "Mascara",
      price: 600,
      img: perfum2,
      images: [perfum2, perfum, perfum3],
      hotsale: true,
      category: "cosmetics",
      inStock: false,
      description:
        "Lengthening mascara with volume boost. Adds drama to your lashes.",
      categories: ["Eye Makeup", "Makeup"],
      tags: ["Mascara", "Volume", "Lengthening"],
    },
    {
      id: 6,
      name: "Compact Powder",
      price: 1000,
      img: perfum3,
      images: [perfum3, perfum, perfum2],
      category: "cosmetics",
      inStock: true,
      description:
        "Translucent powder to set makeup and reduce shine throughout the day.",
      categories: ["Makeup", "Setting Powder"],
      tags: ["Powder", "Setting", "Oil Control"],
    },
    {
      id: 7,
      name: "Nail Polish",
      price: 150,
      img: perfum,
      images: [perfum, perfum2, perfum3],
      hotsale: true,
      category: "cosmetics",
      inStock: true,
      description:
        "High-shine nail polish in trendy colors. Long-lasting and chip-resistant.",
      categories: ["Nail Care", "Beauty"],
      tags: ["Nail Polish", "Glossy", "Trendy"],
    },
    {
      id: 8,
      name: "Perfume",
      price: 3500,
      img: perfum2,
      images: [perfum2, perfum, perfum3],
      newarrival: true,
      category: "cosmetics",
      inStock: false,
      description:
        "Luxurious perfume with floral and woody notes. Long-lasting fragrance.",
      categories: ["Fragrance", "Perfume"],
      tags: ["Perfume", "Fragrance", "Luxury"],
    },
  ],

  "mobile-accessories": [
    {
      id: 9,
      name: "Phone Cover",
      price: 200,
      img: mobile,
      images: [mobile, mobile, mobile],
      hotsale: true,
      category: "mobile-accessories",
      inStock: true,
      description:
        "Protective phone cover with anti-scratch design. Available in multiple colors.",
      categories: ["Mobile Accessories", "Phone Case"],
      tags: ["Phone Cover", "Protective", "Fashion"],
    },
    {
      id: 10,
      name: "Earphones",
      price: 1500,
      img: mobile,
      images: [mobile, mobile, mobile],
      category: "mobile-accessories",
      inStock: true,
      description:
        "Noise-cancelling earphones with premium sound quality and comfortable fit.",
      categories: ["Audio", "Headphones"],
      tags: ["Earphones", "Wireless", "Sound Quality"],
    },
    {
      id: 11,
      name: "Power Bank",
      price: 2500,
      img: mobile,
      images: [mobile, mobile, mobile],
      hotsale: true,
      category: "mobile-accessories",
      inStock: false,
      description:
        "Portable power bank with fast charging technology. Ideal for travel.",
      categories: ["Charger", "Battery"],
      tags: ["Power Bank", "Fast Charging", "Portable"],
    },
    {
      id: 12,
      name: "Wireless Charger",
      price: 3000,
      img: mobile,
      images: [mobile, mobile, mobile],
      hotsale: true,
      newarrival: true,
      category: "mobile-accessories",
      inStock: true,
      description:
        "Qi-certified wireless charger for smartphones. Sleek and modern design.",
      categories: ["Charger", "Wireless"],
      tags: ["Wireless Charger", "Qi", "Smartphone"],
    },
    {
      id: 13,
      name: "Bluetooth Speaker",
      price: 4000,
      img: mobile,
      images: [mobile, mobile, mobile],
      category: "mobile-accessories",
      inStock: true,
      description:
        "Portable Bluetooth speaker with deep bass and 360° sound. Water-resistant.",
      categories: ["Audio", "Speaker"],
      tags: ["Bluetooth", "Portable", "Waterproof"],
    },
    {
      id: 14,
      name: "Smart Watch",
      price: 5500,
      img: mobile,
      images: [mobile, mobile, mobile],
      newarrival: true,
      category: "mobile-accessories",
      inStock: false,
      description:
        "Smartwatch with heart rate monitor, sleep tracker, and fitness apps.",
      categories: ["Wearables", "Smart Devices"],
      tags: ["Smart Watch", "Fitness", "Health"],
    },
    {
      id: 15,
      name: "USB Cable",
      price: 300,
      img: mobile,
      images: [mobile, mobile, mobile],
      category: "mobile-accessories",
      inStock: true,
      description:
        "High-speed USB cable for charging and data transfer. Durable and tangle-free.",
      categories: ["Cable", "Charging"],
      tags: ["USB Cable", "Charging", "Durable"],
    },
    {
      id: 16,
      name: "Car Mount",
      price: 1200,
      img: mobile,
      images: [mobile, mobile, mobile],
      category: "mobile-accessories",
      inStock: true,
      description:
        "Adjustable car mount for smartphones. Secure and easy to use.",
      categories: ["Car Accessories", "Mount"],
      tags: ["Car Mount", "Phone Holder", "Adjustable"],
    },
  ],

  "kitchen-accessories": [
    {
      id: 17,
      name: "Knife Set",
      price: 2000,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      category: "kitchen-accessories",
      inStock: true,
      description:
        "Stainless steel knife set with ergonomic handles. Includes chef's knife, paring knife, and utility knife.",
      categories: ["Kitchen Tools", "Cutlery"],
      tags: ["Knife Set", "Stainless Steel", "Chef Knife"],
    },
    {
      id: 18,
      name: "Non-stick Pan",
      price: 2500,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      category: "kitchen-accessories",
      inStock: true,
      description:
        "Premium non-stick frying pan with even heat distribution. PFOA-free coating.",
      categories: ["Cookware", "Pans"],
      tags: ["Non-stick", "Frying Pan", "Cooking"],
    },
    {
      id: 19,
      name: "Cooking Pot",
      price: 4000,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      hotsale: true,
      category: "kitchen-accessories",
      inStock: false,
      description:
        "Heavy-duty cooking pot with lid. Perfect for soups, stews, and boiling.",
      categories: ["Cookware", "Pot"],
      tags: ["Cooking Pot", "Stew", "Soup"],
    },
    {
      id: 20,
      name: "Pressure Cooker",
      price: 6500,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      category: "kitchen-accessories",
      inStock: true,
      description:
        "Electric pressure cooker with multiple cooking modes. Saves time and energy.",
      categories: ["Appliance", "Cooking"],
      tags: ["Pressure Cooker", "Electric", "Multicooker"],
    },
    {
      id: 21,
      name: "Chopping Board",
      price: 500,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      category: "kitchen-accessories",
      inStock: true,
      description:
        "Large wooden chopping board with juice groove. Easy to clean and durable.",
      categories: ["Kitchen Tools", "Board"],
      tags: ["Chopping Board", "Wooden", "Juice Groove"],
    },
    {
      id: 22,
      name: "Frying Pan",
      price: 2800,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      newarrival: true,
      category: "kitchen-accessories",
      inStock: false,
      description:
        "Non-stick frying pan with handle guard. Ideal for pancakes and eggs.",
      categories: ["Cookware", "Pan"],
      tags: ["Frying Pan", "Non-stick", "Egg Fry"],
    },
    {
      id: 23,
      name: "Spatula Set",
      price: 700,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      category: "kitchen-accessories",
      inStock: true,
      description:
        "Set of silicone spatulas for mixing, scraping, and flipping. Heat-resistant.",
      categories: ["Kitchen Tools", "Utensils"],
      tags: ["Spatula Set", "Silicone", "Heat Resistant"],
    },
    {
      id: 24,
      name: "Glass Set",
      price: 2200,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      hotsale: true,
      category: "kitchen-accessories",
      inStock: true,
      description:
        "Set of 6 elegant drinking glasses. Perfect for water, juice, or cocktails.",
      categories: ["Drinkware", "Glasses"],
      tags: ["Glass Set", "Drinking", "Elegant"],
    },
    {
      id: 25,
      name: "Dinner Set",
      price: 9000,
      img: Kitchen,
      images: [Kitchen, Kitchen, Kitchen],
      hotsale: true,
      category: "kitchen-accessories",
      inStock: false,
      description:
        "Complete dinner set for 6 people. Includes plates, bowls, and cutlery.",
      categories: ["Tableware", "Dinner Set"],
      tags: ["Dinner Set", "Complete", "6 Person"],
    },
  ],
};